# Generated by Django 2.2.7 on 2019-11-18 13:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creation_date', models.DateTimeField(verbose_name='creation date')),
                ('last_edition', models.DateTimeField(verbose_name='edition date')),
            ],
        ),
        migrations.CreateModel(
            name='StorageAction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('date', models.DateTimeField(verbose_name='creation date')),
                ('type', models.CharField(default='Purchase', max_length=8)),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SalesManager.Storage')),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('purchase_date', models.DateTimeField(verbose_name='date of purchase')),
                ('sale_date', models.DateTimeField(blank=True, verbose_name='date of sold')),
                ('batch_code', models.CharField(blank=True, max_length=10)),
                ('purchase_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('sale_price', models.DecimalField(decimal_places=2, default=models.DecimalField(decimal_places=2, max_digits=6), max_digits=6)),
                ('producer_link', models.URLField(blank=True)),
                ('storage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SalesManager.Storage')),
                ('storage_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='SalesManager.StorageAction')),
            ],
        ),
    ]
