# Generated by Django 2.2.7 on 2019-11-20 20:13

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SalesManager', '0003_auto_20191118_1629'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 20, 20, 13, 56, 72973, tzinfo=utc), verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='last_edition',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 20, 20, 13, 56, 72973, tzinfo=utc), verbose_name='edition date'),
        ),
        migrations.AlterField(
            model_name='storageaction',
            name='action_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 20, 20, 13, 56, 341737, tzinfo=utc), verbose_name='real date'),
        ),
        migrations.AlterField(
            model_name='storageaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 20, 20, 13, 56, 341737, tzinfo=utc), verbose_name='creation date'),
        ),
    ]
