# Generated by Django 2.2.7 on 2019-11-25 19:17

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('SalesManager', '0004_auto_20191120_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='storage_action',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='SalesManager.StorageAction'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 25, 19, 17, 6, 752012, tzinfo=utc), verbose_name='creation date'),
        ),
        migrations.AlterField(
            model_name='storage',
            name='last_edition',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 25, 19, 17, 6, 752012, tzinfo=utc), verbose_name='edition date'),
        ),
        migrations.AlterField(
            model_name='storageaction',
            name='action_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 25, 19, 17, 7, 987371, tzinfo=utc), verbose_name='real date'),
        ),
        migrations.AlterField(
            model_name='storageaction',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 25, 19, 17, 7, 987371, tzinfo=utc), verbose_name='creation date'),
        ),
    ]
